const mongoose = require("mongoose")
const Schema = mongoose.Schema;

const dataDetail  =  new Schema(
    {
        peacode:{
            type:String
        },
        office_name:{
            type:String
        },
        ca_no:{
            type:String
        },
        name_customer:{
            type:String
        },
        rate:{
            type:String
        },
        pea_no:{
            type:String
        },
        billing_Cycle:{
            type:String
        },
        year:{
            type:String
        },
        cause:{
            type:String
        },
        in_cause:{
            type:String
        },
        data_broken:{
            normal_date_start:{
                type:String
            },
            normal_date_end:{
                type:String
            },
            brok_date_start:{
                type:String
            },
            brok_date_end:{
                type:String
            },
            p_normal:{
                type:String
            },
            op_normal:{
                type:String
            },
            h_normal:{
                type:String
            },
            sum_normal:{
                type:String
            },
            p_brok:{
                type:String
            },
            op_brok:{
                type:String
            },
            h_brok:{
                type:String
            },
            sum_brok:{
                type:String
            },
            sum_all:{
                type:String
            }
        },
        unit_use:{
            kwh_p:{
                unit_read_after:{
                    type:String
                },
                unit_read_before:{
                    type:String
                },
                multiplier:{
                    type:String
                },
                unit_normal:{
                    type:String
                },
                date_normal:{
                    type:String
                },
                avg_date:{
                    type:String
                },
                date_brok:{
                    type:String
                },
                unit_avg_to_sap:{
                    type:String
                }
            },
            kwh_op:{
                unit_read_after:{
                    type:String
                },
                unit_read_before:{
                    type:String
                },
                multiplier:{
                    type:String
                },
                unit_normal:{
                    type:String
                },
                date_normal:{
                    type:String
                },
                avg_date:{
                    type:String
                },
                date_brok:{
                    type:String
                },
                unit_avg_to_sap:{
                    type:String
                }
            },
            kwh_h:{
                unit_read_after:{
                    type:String
                },
                unit_read_before:{
                    type:String
                },
                multiplier:{
                    type:String
                },
                unit_normal:{
                    type:String
                },
                date_normal:{
                    type:String
                },
                avg_date:{
                    type:String
                },
                date_brok:{
                    type:String
                },
                unit_avg_to_sap:{
                    type:String
                }
            },
            kwh_unit:{
                kwh_p:{
                    unit_read_after:{
                        type:String
                    },
                    unit_read_before:{
                        type:String
                    },
                    multiplier:{
                        type:String
                    },
                    kwh_normal:{
                        type:String
                    }
                },
                kwh_op:{
                    unit_read_after:{
                        type:String
                    },
                    unit_read_before:{
                        type:String
                    },
                    multiplier:{
                        type:String
                    },
                    kwh_normal:{
                        type:String
                    }
                },
                kwh_h:{
                    unit_read_after:{
                        type:String
                    },
                    unit_read_before:{
                        type:String
                    },
                    multiplier:{
                        type:String
                    },
                    kwh_normal:{
                        type:String
                    }
                }
            }
        },
        user:{
            type:String
        },
        createAt:{
            type: Date, default: Date.now
        }
    }
)

module.exports = mongoose.model("DataDetail",dataDetail);